version: '3.4'

services:
  api:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseConfiguration:UseInMemory=false
      - DatabaseConfiguration:ConnectionString=User ID=postgres;Password=example;Server=db;Port=5432;Database=API_DB;Integrated Security=true;Pooling=true;
      - JWTConfiguration:Secret=Docker-Secret-356178he9j20kle
    networks:
      - api
    ports:
      - "5020:80"
    depends_on: 
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - api

  pg-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
        - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - api

networks: 
  api:
    
volumes: 
  pgdata:
  pgadmin:

