version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile

  integrationtests:
    image: ${DOCKER_REGISTRY-}integrationtests
    build:
      context: .
      dockerfile: Tests/IntegrationTests/Dockerfile


  unittests:
    image: ${DOCKER_REGISTRY-}unittests
    build:
      context: .
      dockerfile: Tests/UnitTests/Dockerfile

